# Generated by Django 3.2.7 on 2021-09-24 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comments_follwers_likes_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='C',
            new_name='post',
        ),
    ]
