# Generated by Django 3.2.7 on 2021-09-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_posts_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follwers',
            name='follower',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='follwers',
            name='follwing',
            field=models.CharField(max_length=256),
        ),
    ]
