# Generated by Django 3.2.7 on 2021-09-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_likes_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
    ]
